### ISSUE TITLE
Just shows random songs changing per second in opera

### ISSUE THREAD

**Issue by RayyanNafees** [avyuktsoni0731/musicPlayerGDSCTask1#1]
For further advancements, consider the following:

# Libraries to consider
- **Audio**: Use [Howler.js](https://github.com/goldfire/howler.js#documentation) for playing the music
-  **Music**:  [TheAudioDB](https://www.theaudiodb.com/free_music_api) API for getting any music audio u want
- **Background Color Change**: A Glassmorphic effect will look amazing on the project, follow [this short article](https://albertwalicki.com/blog/glassmorphism-how-to-create) to implement simple CSS styling for the background, then change the blurred color
- **Stop changing on hover**: `clearInterval` when the user hover overs the card to set music, tracked by `.onmouseenter` event 
and again `setInterval` when the mouse unhovers over the card, marked by `.onmouseleave` event 

# Example projects
- Checkout [astro-records](https://github.com/Charca/astro-records/blob/main/src/pages/index.astro) project, for the reference for implementing TheAudioDB api, like [this](https://astro-records.netlify.app)

**Comment by avyuktsoni0731** [comment]
@RayyanNafees Yea the Play/Pause button is a bit glitchy, I tried to make it work, but if you click on the **i** tag itself, it doesnt work, but the **button** tag as a whole works. Can you please elaborate more on what did you find not working in the project? So that i can directly work on that, coz i've tested it multiple times, works just fine for me.

Sure, i'll look into the links you have attached, and try to make a better project, i currently knew the basic logic of JS, so i was able to do this only.

Thanks :)

**Comment by RayyanNafees** [comment]
My bad.. I use Opera as my go-to browser... it was just changing music and I couldn't click on Play there
Just checked in Edge and it worked!
My apologies

btw, U should checkout jQuery
I had trouble with js initially and jQuery helped me alot for making up for the logic

> Please do close the issue since it was just a browser issue

**Comment by avyuktsoni0731** [comment]
@RayyanNafees No worries man! Thanks for letting me know that it have some issues on Opera, i'll test it by myself and try to work on that issue if something is faulty from my end.
